# Generated by Django 2.2 on 2019-05-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='操作用户的主键')),
                ('affect_ware', models.CharField(choices=[('Supplier', '供应商'), ('Classification', '储物分类'), ('InWarehouse', '入库记录单'), ('OutWarehouse', '出库记录单'), ('Warehouse', '储物库'), ('Sale', '销售单')], max_length=32, verbose_name='受影响的表')),
                ('affect_object_id', models.IntegerField(verbose_name='受影响表的对象主键')),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('MODIFY', '修改'), ('DELETE', '删除')], max_length=16, verbose_name='用户活动描述')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='活动发生时间')),
            ],
            options={
                'verbose_name': '用户操作记录',
                'verbose_name_plural': '用户操作记录',
                'db_table': 'w_history',
                'ordering': ['-id', '-create_date'],
            },
        ),
    ]
