# Generated by Django 2.2 on 2019-05-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_history_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True, verbose_name='用户主键')),
                ('level', models.CharField(choices=[('REGISTRATION', '注册请求'), ('MESSAGE', '普通消息')], max_length=16, verbose_name='消息级别')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='消息发出时间')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否处理完成')),
            ],
            options={
                'verbose_name': '用户消息记录',
                'verbose_name_plural': '用户消息记录',
                'db_table': 'w_notification',
                'ordering': ['-id', '-create_date'],
            },
        ),
    ]
