# Generated by Django 2.2 on 2019-04-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否标记删除'),
        ),
        migrations.AddField(
            model_name='inwarehouse',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否标记删除'),
        ),
        migrations.AddField(
            model_name='outwarehouse',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否标记删除'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否标记删除'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否标记删除'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否标记删除'),
        ),
    ]
