# Generated by Django 2.2 on 2019-05-29 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='物品种类')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否标记删除')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'w_classification',
            },
        ),
        migrations.CreateModel(
            name='OutWareHouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('good_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='储物编号')),
                ('good_name', models.CharField(max_length=64, verbose_name='储物名称')),
                ('spec', models.CharField(default='未定义', max_length=32, verbose_name='规格/型号')),
                ('out_amount', models.IntegerField(default=0, verbose_name='数量')),
                ('unit', models.CharField(default='未定义', max_length=32, verbose_name='计件单位')),
                ('out_price', models.FloatField(default=0, verbose_name='总金额')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否完成')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否标记删除')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outWarehouse', to='warehouse.Classification')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单',
                'db_table': 'w_out_warehouse',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='供应商编号')),
                ('supplier_name', models.CharField(max_length=64, verbose_name='供应商名称')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否标记删除')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'w_supplier',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('good_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='储物编号')),
                ('good_name', models.CharField(max_length=64, verbose_name='储物名称')),
                ('spec', models.CharField(default='未定义', max_length=32, verbose_name='规格/型号')),
                ('amount', models.IntegerField(default=0, verbose_name='数量')),
                ('unit', models.CharField(default='未定义', max_length=32, verbose_name='计件单位')),
                ('price', models.FloatField(default=0, verbose_name='总金额')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否标记删除')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='warehouse.Classification')),
                ('supplier', models.ForeignKey(on_delete=models.SET('数据删除'), related_name='warehouse', to='warehouse.Supplier')),
            ],
            options={
                'verbose_name': '储物库',
                'verbose_name_plural': '储物库',
                'db_table': 'w_warehouse',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('good_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='商品编号')),
                ('good_name', models.CharField(max_length=64, verbose_name='商品名称')),
                ('spec', models.CharField(default='未定义', max_length=32, verbose_name='规格/型号')),
                ('out_amount', models.IntegerField(default=0, verbose_name='数量')),
                ('unit', models.CharField(default='未定义', max_length=32, verbose_name='计件单位')),
                ('out_price', models.FloatField(default=0, verbose_name='销售金额')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否完成')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否标记删除')),
                ('remark', models.TextField(null=True, verbose_name='备注')),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='warehouse.Classification')),
                ('good_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='warehouse.OutWareHouse')),
                ('supplier', models.ForeignKey(on_delete=models.SET('数据删除'), related_name='sale', to='warehouse.Supplier')),
            ],
            options={
                'verbose_name': '销售单',
                'verbose_name_plural': '销售单',
                'db_table': 'w_sale',
            },
        ),
        migrations.AddField(
            model_name='outwarehouse',
            name='supplier',
            field=models.ForeignKey(on_delete=models.SET('数据删除'), related_name='outWarehouse', to='warehouse.Supplier'),
        ),
        migrations.CreateModel(
            name='InWarehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('good_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='储物编号')),
                ('good_name', models.CharField(max_length=64, verbose_name='储物名称')),
                ('spec', models.CharField(default='未定义', max_length=32, verbose_name='规格/型号')),
                ('in_amount', models.IntegerField(default=0, verbose_name='数量')),
                ('unit', models.CharField(default='未定义', max_length=32, verbose_name='计件单位')),
                ('in_price', models.FloatField(default=0, verbose_name='总金额')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否完成')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否标记删除')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inWarehouse', to='warehouse.Classification')),
                ('supplier', models.ForeignKey(on_delete=models.SET('数据删除'), related_name='inWarehouse', to='warehouse.Supplier')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单',
                'db_table': 'w_in_warehouse',
            },
        ),
    ]
