# Generated by Django 2.2 on 2019-04-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20190420_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='remark',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='inwarehouse',
            name='remark',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='outwarehouse',
            name='remark',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='remark',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='remark',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='remark',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
    ]
