# Generated by Django 2.2 on 2019-05-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20190529_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwarehouse',
            name='recipient',
            field=models.CharField(default='无描述', max_length=64, verbose_name='接收方'),
        ),
    ]
