# Generated by Django 2.2 on 2019-05-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20190422_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('CREATE', '创建'), ('MODIFY', '修改'), ('DELETE', '删除')], max_length=16, verbose_name='用户活动描述'),
        ),
        migrations.AlterField(
            model_name='history',
            name='affect_id',
            field=models.IntegerField(verbose_name='受影响的对象主键'),
        ),
    ]
