# Generated by Django 2.2 on 2019-05-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20190528_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
